# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250)),
                ('aciklama', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='etiket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=250)),
                ('govde', models.TextField()),
                ('ekleme_tarihi', models.DateField(default=django.utils.timezone.now)),
                ('yayinda_mi', models.BooleanField(default=1)),
                ('slug', models.SlugField(unique=True)),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
